services:
  Dvc\ContaoAjaxReloadElementBundle\EventListener\AjaxReloadElementListener:
    public: true
    arguments:
      - '@contao.image.picture_factory'
  
  Dvc\ContaoAjaxReloadElementBundle\EventListener\DataContainer\ModifyPalettesListener:
    public: true
