services:
  _defaults:
    autowire: true
    autoconfigure: true

  Richardhj\ContaoAjaxReloadElementBundle\:
    resource: ../../*
    exclude:
      - ../../ContaoManager/
      - ../../DependencyInjection/
      - ../../Resources/
